dashboard:
  build: .
  dockerfile: Dockerfile
web:
  build: .
  dockerfile: Dockerfile-dev
  links:
    - db
  environment:
    - DB_HOST=db
  ports:
    - '8086:8086'
  command: npm start
db:
  image: mongo

